# Generated by Django 4.1.1 on 2023-02-06 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(upload_to='static')),
                ('image2', models.ImageField(upload_to='static')),
                ('image3', models.ImageField(upload_to='static')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('file1', models.FileField(upload_to='static')),
                ('file2', models.FileField(upload_to='static')),
                ('file3', models.FileField(upload_to='static')),
                ('closed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
