# Generated by Django 4.1.1 on 2023-02-06 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_projects_delete_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='user',
        ),
    ]
